### ISSUE TITLE
Video Settings Crash

### ISSUE THREAD

**Issue by WhoPlaysTheFool** [Zanieon/NorthstarMods#7]
Crash when attempting to open video settings from main menu (FD branch)
[nslog2024-05-14 16-46-29.txt](https://github.com/Zanieon/NorthstarMods/files/15303962/nslog2024-05-14.16-46-29.txt)
[nsdump2024-05-14 16-46-57.dmp](https://github.com/Zanieon/NorthstarMods/files/15303969/nsdump2024-05-14.16-46-57.dmp)

**Comment by Zanieon** [comment]
Well closing the issue as apparently it was a GPU Driver issue and not the issue with Northstar itself or the FD branch.
