### ISSUE TITLE
fd not working correctly

### ISSUE THREAD

**Issue by marcocancarini** [Zanieon/NorthstarMods#9]
I'm hosting on dockers (linux mint) 
I run the script to download the files and also copying them from my pc
I copy paste the folders but i'm stuck at final wave without choosing the titan
here my docker-compose.yml 
[https://pastebin.com/ZDQ0mVVh](url)

**Comment by Zanieon** [comment]
You're halfchemistry on discord right? i was literally replying to you in there, posting the issue in here won't help much, someone else with more linux experience than me will be needed to help with this issue.

**Comment by marcocancarini** [comment]
Sorry i wanted to open a issue under the fd mod but somehow i fcked up. Sorry and thank you for your help
